### PR TITLE
Fixed validation on required boolean false

### PR DESCRIPTION
**Pull request by jdylanstewart**
Now works for false Boolean values while still having desired check against undefined

### CODE REVIEW

**Comment by zackiles** [comment]
Thank you sir.

**Comment by jdylanstewart** [comment]
I did a second feature edit on that branch that got pulled into the PR.

I changed the toObject method to only pick up properties defined in the schema if a schema was present. I'm not sure that is a feature you want to be including or not, it was just something I found useful as I am using `dynamic: 'strict'` schemas.

**Comment by zackiles** [comment]
Seems OK to me. Thanks for your contribution. Maybe you could help me with making this support 2.0+ versions of ElasticSearch? I only use this at work in 1.7.4 and I've been told it doesn't work in 2.0+

**Comment by bloublou2014** [comment]
For info i worked on ES2.x ES5.x support https://github.com/bloublou2014/elasticsearch-odm/ and https://github.com/bloublou2014/elasticsearch-odm/tree/es-5.x 

it's working fine for my use but i ve not tested all cases.

**Comment by jdylanstewart** [comment]
My work is actually still living in 1.7 world, otherwise, I would definitely help out.

**Pull request merged**
